# TCL File Generated by Component Editor 17.1
# Sun Apr 01 21:17:51 MSK 2018
# DO NOT MODIFY


# 
# h2f_bridge_dsp "h2f_bridge_dsp" v1.0
#  2018.04.01.21:17:51
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 15.1


# 
# module h2f_bridge_dsp
# 
set_module_property DESCRIPTION ""
set_module_property NAME h2f_bridge_dsp
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME h2f_bridge_dsp
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL h2f_bridge_dsp
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file h2f_bridge_dsp.sv SYSTEM_VERILOG PATH ../../code/synt/user_qsys_comp/h2f_bridge_dsp.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter WIDTH_ADDR INTEGER 9 ""
set_parameter_property WIDTH_ADDR DEFAULT_VALUE 9
set_parameter_property WIDTH_ADDR DISPLAY_NAME WIDTH_ADDR
set_parameter_property WIDTH_ADDR TYPE INTEGER
set_parameter_property WIDTH_ADDR UNITS None
set_parameter_property WIDTH_ADDR ALLOWED_RANGES -2147483648:2147483647
set_parameter_property WIDTH_ADDR DESCRIPTION ""
set_parameter_property WIDTH_ADDR HDL_PARAMETER true
add_parameter WIDTH_DATA INTEGER 32
set_parameter_property WIDTH_DATA DEFAULT_VALUE 32
set_parameter_property WIDTH_DATA DISPLAY_NAME WIDTH_DATA
set_parameter_property WIDTH_DATA TYPE INTEGER
set_parameter_property WIDTH_DATA UNITS None
set_parameter_property WIDTH_DATA ALLOWED_RANGES -2147483648:2147483647
set_parameter_property WIDTH_DATA HDL_PARAMETER true
add_parameter WIDTH_BE INTEGER 4 ""
set_parameter_property WIDTH_BE DEFAULT_VALUE 4
set_parameter_property WIDTH_BE DISPLAY_NAME WIDTH_BE
set_parameter_property WIDTH_BE TYPE INTEGER
set_parameter_property WIDTH_BE UNITS None
set_parameter_property WIDTH_BE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property WIDTH_BE DESCRIPTION ""
set_parameter_property WIDTH_BE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avl
# 
add_interface avl avalon end
set_interface_property avl addressUnits WORDS
set_interface_property avl associatedClock clock_dsp
set_interface_property avl associatedReset reset
set_interface_property avl bitsPerSymbol 8
set_interface_property avl burstOnBurstBoundariesOnly false
set_interface_property avl burstcountUnits WORDS
set_interface_property avl explicitAddressSpan 0
set_interface_property avl holdTime 0
set_interface_property avl linewrapBursts false
set_interface_property avl maximumPendingReadTransactions 0
set_interface_property avl maximumPendingWriteTransactions 0
set_interface_property avl readLatency 2
set_interface_property avl readWaitTime 1
set_interface_property avl setupTime 0
set_interface_property avl timingUnits Cycles
set_interface_property avl writeWaitTime 0
set_interface_property avl ENABLED true
set_interface_property avl EXPORT_OF ""
set_interface_property avl PORT_NAME_MAP ""
set_interface_property avl CMSIS_SVD_VARIABLES ""
set_interface_property avl SVD_ADDRESS_GROUP ""

add_interface_port avl avl_write write Input 1
add_interface_port avl avl_chipselect chipselect Input 1
add_interface_port avl avl_waitrequest waitrequest Output 1
add_interface_port avl avl_address address Input WIDTH_ADDR
add_interface_port avl avl_byteenable byteenable Input WIDTH_BE
add_interface_port avl avl_readdata readdata Output WIDTH_DATA
add_interface_port avl avl_writedata writedata Input WIDTH_DATA
set_interface_assignment avl embeddedsw.configuration.isFlash 0
set_interface_assignment avl embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avl embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avl embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_dsp
# 
add_interface clock_dsp clock end
set_interface_property clock_dsp clockRate 0
set_interface_property clock_dsp ENABLED true
set_interface_property clock_dsp EXPORT_OF ""
set_interface_property clock_dsp PORT_NAME_MAP ""
set_interface_property clock_dsp CMSIS_SVD_VARIABLES ""
set_interface_property clock_dsp SVD_ADDRESS_GROUP ""

add_interface_port clock_dsp clk_dsp clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock_dsp
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock_dsp
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master avl_write_dsp write Output 1
add_interface_port avalon_master avl_chipselect_dsp chipselect Output 1
add_interface_port avalon_master avl_address_dsp address Output WIDTH_ADDR
add_interface_port avalon_master avl_byteenable_dsp byteenable Output WIDTH_BE
add_interface_port avalon_master avl_readdata_dsp readdata Input WIDTH_DATA
add_interface_port avalon_master avl_writedata_dsp writedata Output WIDTH_DATA

